#!/usr/bin/env python2

#import rospy
import serial
import re
#from std_msgs.msg import Float64, Float32, Header, Time
#from sensor_msgs.msg import Laserscan

Arduino = '/dev/ttyACM0'
Baud = 115200


def serial_listen():
    while True:
        sensor = serial.Serial(Arduino, Baud)
        x = sensor.readline()
        xshort = x[0:-2]
        split = xshort.split(",")
        #split = split.splitlines()
        #print x
        #print xshort
        print split
        

if __name__ == '__main__':
	serial_listen()
